(function(){function z(b,c,d){function e(b,c){if(!b)return null;var d="",f=null;if(b.childNodes&&0<b.childNodes.length)for(var g=0;g<b.childNodes.length;g++){var k=b.childNodes[g],m=k.nodeType,l=k.localName||k.nodeName||"",i=k.text||k.nodeValue||"";if(8!=m)if(3==m||4==m||!l)d+=i.replace(/^\s+|\s+$/g,"");else if(f=f||{},f[l]){if(!(f[l]instanceof Array)||!f[l].length)f[l]=[f[l]];f[l].push(e(k,!0))}else f[l]=e(k,!1)}if(b.attributes&&!j&&0<b.attributes.length){f=f||{};for(k=0;k<b.attributes.length;k++)l=
b.attributes[k],m=l.name||"",l=l.value,f[m]?(!(f[m]instanceof Array)&&f[m].length&&(f[m]=[f[m]]),f[m].push(l)):f[m]=l}if(f){if(""!=d){k=new String(d);for(g in f)k[g]=f[g];f=k}if(d=f.text?("object"==typeof f.text?f.text:[f.text||""]).concat([d]):d)f.text=d;d=""}f=f||d;if(h){d&&(f={});if(d=f.text||d||"")f.text=d;!c&&!(f instanceof Array)&&(f=[f])}return f}var h=c,j=d;if(!b)return{};"string"==typeof b&&(b=A(b));if(b.nodeType){if(3==b.nodeType||4==b.nodeType)return b.nodeValue;b=9==b.nodeType?b.documentElement:
b;c=e(b,!0);b=b=null;return c}}function A(b){var c;try{var d=new DOMParser;d.async=!1;c=d.parseFromString(b,"text/xml")}catch(e){throw Error("Error parsing XML string");}return c}function B(b){function c(b,c){var d=(b&65535)+(c&65535);return(b>>16)+(c>>16)+(d>>16)<<16|d&65535}var d;d=[];for(var e=0;e<8*b.length;e+=8)d[e>>5]|=(b.charCodeAt(e/8)&255)<<24-e%32;b=8*b.length;d[b>>5]|=128<<24-b%32;d[(b+64>>9<<4)+15]=b;for(var b=Array(80),e=1732584193,h=-271733879,j=-1732584194,o=271733878,g=-1009589776,
n=0;n<d.length;n+=16){for(var f=e,p=h,k=j,m=o,l=g,i=0;80>i;i++){b[i]=16>i?d[n+i]:(b[i-3]^b[i-8]^b[i-14]^b[i-16])<<1|(b[i-3]^b[i-8]^b[i-14]^b[i-16])>>>31;var q=c(c(e<<5|e>>>27,20>i?h&j|~h&o:40>i?h^j^o:60>i?h&j|h&o|j&o:h^j^o),c(c(g,b[i]),20>i?1518500249:40>i?1859775393:60>i?-1894007588:-899497514)),g=o,o=j,j=h<<30|h>>>2,h=e,e=q}e=c(e,f);h=c(h,p);j=c(j,k);o=c(o,m);g=c(g,l)}d=[e,h,j,o,g];b="";for(e=32;--e;){for(h=a=0;h<d.length;h++)a+=(d[h]&1)<<h,d[h]>>=1;b+="hzv4ut7rpmed91yw5ik6n8sobax32gfcy2y0f3e1a8r9t6h"[a]}return b}
var p,r,t,u,g,v,s,w,n,x,y,q=function(b,c){return function(){return b.apply(c,arguments)}};window.app={back:function(){return history.go(-1)}};location.hash="#home";$('[data-role="page"] [data-role="header"]:not(.ui-non-nav)').append($('[data-btn-role="back"],[data-btn-role="home"]'));$('#search [data-btn-role="home"]').hide();p=document.body;v=$(document.querySelectorAll('[data-role="map"]'));$(window).resize(function(){console.log("resize",p.clientWidth,p.clientHeight);app.horizontal=p.clientWidth>
p.clientHeight;return $(p)[app.horizontal?"addClass":"removeClass"]("horizontal")});$(document.body).resize();$("#home").one({pageshow:function(){return g.el.offset($("#home_map").offset())}});g=app.map=new google.maps.Map($("#map")[0],{zoom:15,mapTypeId:google.maps.MapTypeId.ROADMAP,navigationControl:!0,navigationControlOptions:{style:google.maps.NavigationControlStyle.SMALL}});s=new google.maps.places.PlacesService(g);u=new google.maps.Geocoder;t=new google.maps.DirectionsService;r=new google.maps.DirectionsRenderer;
x=new google.maps.LatLngBounds(new google.maps.LatLng(38.052417,-122.728271),new google.maps.LatLng(37.247821,-121.552734));(function(){this.el=$("#map");(new google.maps.TrafficLayer).setMap(this);return $.extend(this,{setMarkers:q(function(b){console.log("markers",b);b?$.isArray(b)||(b=[b]):b=null;null!=this.markers&&this.markers.forEach(function(b){return b.setMap(null)});this.markers=null!=b?b.map(function(b){b.map=g;return new google.maps.Marker(b)}):null;return this},this),getCurPos:q(function(b,
c){null==c&&(c=b,b=!0);null!=navigator.geolocation&&navigator.geolocation.getCurrentPosition(q(function(d){var e;e=new google.maps.LatLng(d.coords.latitude,d.coords.longitude);console.log("curlatlng",e);if(!e.equals(this.getCenter()))e.changed=!0;return b&&e.changed?(this.setMarkers(null),this.setCenter(e),v.each(q(function(b,c){return $(c).css("background-image","url('https://maps.googleapis.com/maps/api/staticmap?center="+e.lat()+","+e.lng()+"&zoom="+($(c).attr("data-map-zoom")||15)+"&size="+$(window).width()+
"x"+this.el.height()+"&maptype=roadmap&format=png8&sensor=true&language=en')")},this)),u.geocode({latLng:e},q(function(b,d){var g;d===google.maps.GeocoderStatus.OK?c.call(this,e,null!=(g=b[0])?g.formatted_address:void 0):alert("Geocoder failed due to: "+d+"\n App terminated!");return this.setCenter(e)},this))):c.call(this,e)},this),function(){return alert("App cannot run without geo location!")});return this},this)})}).call(g);$('[data-role="page"]').bind({pagebeforeshow:function(){return g.el.css({opacity:0,
"z-index":0})},pageshow:function(){var b,c;$.mobile.fixedToolbars.show();this.hh=(null!=(b=$('[data-role="header"]',this))?b.outerHeight():void 0)||0;this.fh=(null!=(c=$('[data-role="footer"]',this))?c.outerHeight():void 0)||0;this.bh=document.body.clientHeight-this.hh-this.fh;$(".map",this).add(g.el).height(this.bh*(app.horizontal?1:0.45));if($(this).hasClass("has-map"))return g.el.css({opacity:1,"z-index":1E4})}});$("#home").bind({pagebeforeshow:function(){if(!("undefined"!==typeof n&&null!==n)||
32!==n.length)$.mobile.changePage("#login",{transition:"none"});else if(!$("#map",this).length)return console.log("home pageshow"),g.getCurPos(function(b,c){null!=c&&$("#home_addr").text(c);this.setZoom(15);return this.setMarkers({position:b})}),this}});n=sessionStorage.sid||localStorage.sid;y=function(b){$.mobile.showPageLoadingMsg();$.ajax({url:"svc/"+b.svc+".svc/"+b.method,type:"POST",dataType:"json",contentType:"application/json;charset=utf-8",data:JSON.stringify(b.data),processdata:!1,complete:function(){$.mobile.hidePageLoadingMsg();
return"function"===typeof b.complete?b.complete():void 0},success:function(c,d){if(null!=(null!=c?c.d:void 0))return b.callback(c.d);alert("Network Error");return console.log("err",d,d.statusText)},error:function(b){alert("Network Error");return console.log("err",b,b.statusText)}});return!1};$("#login").bind({pagecreate:function(){return $("#login_form").bind({submit:function(b){var c,d,e,g,j;b.preventDefault();b.stopPropagation();g=$("input",this).textinput("disable");j=$("select",this).slider("disable");
d=$("button",this).button("disable");$("#btn_reg").addClass("ui-disabled");e=$("#email").val().trim();b=$("#password").val();if(!e||!b)return!1;b=B("\x00"+e+"\u00ffKnightRider\u00ff"+b+"\x00X\u00b5\u0004\u0005\u00f1PGo\u00f0@\u00d8\u00f4\u00ed\u009d\u00d2y\u00c0n\u00a6\u00d9\u00ff");c="on"===$("#autologin").val();y({svc:"user",method:"login",data:{email:e,password:b},callback:function(b){var f;var d;console.log(b);if(b.uid&&32===(null!=(d=b.sid)?d.length:void 0)){n=sessionStorage.sid=b.sid;if(c)localStorage.sid=
n;f=sessionStorage.user={uid:b.uid,email:e},b=f;if(c)localStorage.user=b;return $.mobile.changePage("#home",{transition:"flip"})}return alert("Login Failed, please try again")},complete:function(){d.button("enable");g.textinput("enable");j.slider("enable");return $("#btn_reg").removeClass("ui-disabled")}});return this}})},pagebeforehide:function(){return $("#login_form_warp").hide()},pagebeforeshow:function(){return $("#login_form_warp").hide()},pageshow:function(){$("#login_form_warp").show();return localStorage.sid=
sessionStorage.sid=n=null}});$.ajax({url:"gapi?&hl=en-us&weather=san+jose,ca",dataType:"xml",success:function(b){var c,d,b=z(b);if(null!=(null!=(c=b.weather)?c.current_conditions:void 0))return c=b.weather.current_conditions,console.log("w:",b),d=function(b){return"https://www.google.com"+b.icon.data},$("#weather").html('<div id="weather_now" class="weather"><img src="'+d(c)+'"/>'+c.condition.data+"<br/>"+c.temp_f.data+"\u00b0F</div>").append(b.weather.forecast_conditions.map(function(b){return'<div class="weather"><img src="'+
d(b)+'"/>'+b.day_of_week.data+" "+b.high.data+"/"+b.low.data+"\u00b0F</div>"}).join("")),this},error:function(b){return console.log("get weather failed",b)}});try{console.log(localStorage.custom_search_history);if(null!=localStorage.custom_search_history)app.history=JSON.parse(localStorage.custom_search_history);if(!$.isArray(app.history))app.history=[]}catch(C){console.log(C),app.history=[]}finally{app.history.refresh=q(function(){$("#history_list li:gt(0)").remove();return app.history.length?$("#history_list_header").after(app.history.map(function(b){return'<li><a href="#result" data-btn-role="search">'+
b+"</a></li>"}).join("")):$("#history_list_header").after('<li data-role="list-divider" class="ui-body-c list-none">(None)</li>')},this)}$('[data-btn-role="search"]').live({vclick:function(){app.search_keyword=$(this).text();console.log("vclick",app.search_keyword);return this}});$("#search_history").bind({pagecreate:function(){this.created=!0;app.history.refresh();return new google.maps.places.Autocomplete($("#input_search")[0],{bounds:x,types:["establishment"]})}});$("#search_history").bind("pageshow pagebeforeshow",
function(){if(this.created)return $("#history_list").listview("refresh")});$("#custom_search_form").submit(function(){var b,c;b=$("#input_search");(c=$.trim(b.val()))?(app.search_keyword=c,$.mobile.changePage("#result"),console.log("vclick",app.history.search_keyword)):b.focus().val("");return!1});window.onbeforeunload=function(){localStorage.custom_search_history=JSON.stringify(app.history)};$("#result").bind({pageshow:function(){var b;console.log("search for",app.search_keyword);if(app.search_keyword)return b=
$("#result_list").empty(),g.getCurPos(function(c){this.setZoom(12);return s.search({location:c,radius:5E3,keyword:app.search_keyword},function(d,e){var h;e===google.maps.places.PlacesServiceStatus.ZERO_RESULTS?(alert("Zero Result"),app.back()):e===google.maps.places.PlacesServiceStatus.OK?($("#result_addr").text(""+app.search_keyword+" ("+d.length+")"),b.height(document.body.clientHeight-b.offset().top),console.log("search result",d),app.result_map={},d.forEach(function(b){var d,e;app.result_map[b.id]=
b;b=b.geometry;e=b.location.lng()-c.lng();d=b.location.lat()-c.lat();return b.dist=Math.pow(e,2)+Math.pow(d,2)}),d.sort(function(b,c){return b.geometry.dist-c.geometry.dist}),d=d.slice(0,25),b.append(d.map(function(b,c){var d;b.seq=String.fromCharCode(65+c);return'<li><a href="#detail" data-btn-role="result" id="'+b.id+'"><div style="float:left">'+b.seq+'</div><img src="'+(null!=(d=b.icon)?d.replace(/^http:/,"https:"):void 0)+'" class="ui-li-icon"><h3 class="ui-li-heading">'+b.name+'</h3><p class="ui-li-desc">'+
b.vicinity+"</p></li>"}).join("")),h=d.reverse().map(function(b){return{position:b.geometry.location,icon:"https://www.google.com/mapfiles/marker"+b.seq+".png",title:b.name}}),b.listview("refresh"),h.push({position:c,icon:"https://www.google.com/mapfiles/arrow.png",title:"You are here"}),g.setMarkers(h),app.history[0]!==app.search_keyword&&(app.history.unshift(app.search_keyword),app.history.refresh())):alert("Search Error");return this})}),this;app.back()}});w=function(b){var c,d,b=Number(b);d=b.toFixed(1);
c=b|0;0<c&&(d+=" "+Array(c+1).join('<img src="res/star.png"/>'));0.4<b-c&&(d+='<img src="res/halfstar.png"/>');return d};$("#result_list a").live({vclick:function(){console.log(this.id);return app.selected_place=app.result_map[this.id]}});$("#detail").bind({pageshow:function(){var b;b=$("#detial_info");b.height(document.body.clientHeight-b.offset().top-this.fh);console.log("detailof",app.selected_place);window.scrollTop=0;if(app.selected_place)return $("#apt_cancel").bind({vclick:function(b){b.preventDefault();
b.stopPropagation();$("#appointment").dialog("close");return!1}}),s.getDetails({reference:app.selected_place.reference},function(c,d){if(d===google.maps.places.PlacesServiceStatus.OK)return g.setCenter(c.geometry.location),g.setMarkers({position:c.geometry.location}),g.setZoom(15),$("#detail_place").text(c.name),b.html("<ul><li>"+c.formatted_address+"</li><li>"+c.formatted_phone_number+"</li><li>"+c.types.join(", ").replace(/_/g," ").toUpperCase()+"</li><li>"+(null!=c.rating?w(c.rating):"(No Rating Data)")+
'</li><li><a href="'+(c.website||c.url)+'" target="_blank">'+(null!=c.website?"Visit its Website":"View on Google Place")+"</a></li></ul>"),console.log(c)});app.back()}});$("#direction").bind({pageshow:function(){var b;b=$("#direction_panel");b.height(document.body.clientHeight-b.offset().top);return g.getCurPos(function(c,d){return t.route({origin:d,destination:app.selected_place.vicinity,travelMode:google.maps.DirectionsTravelMode.DRIVING,unitSystem:google.maps.DirectionsUnitSystem.IMPERIAL,provideRouteAlternatives:!0},
function(c,d){var j;return d===google.maps.DirectionsStatus.OK?(r.setMap(g),r.setPanel(b[0]),r.setDirections(c),function(){return g.getCurPos(function(b,c){return this.setMarkers({position:null!=c?b:void 0})})}()):alert("Directions failed: "+d)})})},pagehide:function(){return r.setMap(null)}});console.log(2)}).call(this);
