(function(){function C(a,b,c){function d(a,c){if(!a)return null;var b="",e=null;if(a.childNodes&&0<a.childNodes.length)for(var f=0;f<a.childNodes.length;f++){var k=a.childNodes[f],l=k.nodeType,g=k.localName||k.nodeName||"",j=k.text||k.nodeValue||"";if(8!=l)if(3==l||4==l||!g)b+=j.replace(/^\s+|\s+$/g,"");else if(e=e||{},e[g]){if(!(e[g]instanceof Array)||!e[g].length)e[g]=[e[g]];e[g].push(d(k,!0))}else e[g]=d(k,!1)}if(a.attributes&&!i&&0<a.attributes.length){e=e||{};for(k=0;k<a.attributes.length;k++)g=
a.attributes[k],l=g.name||"",g=g.value,e[l]?(!(e[l]instanceof Array)&&e[l].length&&(e[l]=[e[l]]),e[l].push(g)):e[l]=g}if(e){if(""!=b){k=new String(b);for(f in e)k[f]=e[f];e=k}if(b=e.text?("object"==typeof e.text?e.text:[e.text||""]).concat([b]):b)e.text=b;b=""}e=e||b;if(h){b&&(e={});if(b=e.text||b||"")e.text=b;!c&&!(e instanceof Array)&&(e=[e])}return e}var h=b,i=c;if(!a)return{};"string"==typeof a&&(a=E(a));if(a.nodeType){if(3==a.nodeType||4==a.nodeType)return a.nodeValue;a=9==a.nodeType?a.documentElement:
a;b=d(a,!0);a=a=null;return b}}function E(a){var b;try{var c=new DOMParser;c.async=!1;b=c.parseFromString(a,"text/xml")}catch(d){throw Error("Error parsing XML string");}return b}function t(a){for(var b=[],c=0;c<8*a.length;c+=8)b[c>>5]|=(a.charCodeAt(c/8)&255)<<24-c%32;a=8*a.length;b[a>>5]|=128<<24-a%32;b[(a+64>>9<<4)+15]=a;for(var a=Array(80),c=1732584193,d=-271733879,h=-1732584194,i=271733878,f=-1009589776,q=0;q<b.length;q+=16){for(var D=c,e=d,m=h,k=i,l=f,g=0;80>g;g++){a[g]=16>g?b[q+g]:(a[g-3]^
a[g-8]^a[g-14]^a[g-16])<<1|(a[g-3]^a[g-8]^a[g-14]^a[g-16])>>>31;var n=j(j(c<<5|c>>>27,20>g?d&h|~d&i:40>g?d^h^i:60>g?d&h|d&i|h&i:d^h^i),j(j(f,a[g]),20>g?1518500249:40>g?1859775393:60>g?-1894007588:-899497514)),f=i,i=h,h=d<<30|d>>>2,d=c,c=n}c=j(c,D);d=j(d,e);h=j(h,m);i=j(i,k);f=j(f,l)}b=[c,d,h,i,f];a="";for(c=0;c<4*b.length;c++)a+="0123456789abcdef".charAt(b[c>>2]>>8*(3-c%4)+4&15)+"0123456789abcdef".charAt(b[c>>2]>>8*(3-c%4)&15);return a}function j(a,b){var c=(a&65535)+(b&65535);return(a>>16)+(b>>16)+
(c>>16)<<16|c&65535}var m,o,u,v,r,f,w,s,x,y,n,z,A,B,p=function(a,b){return function(){return a.apply(b,arguments)}};window.app={back:function(){return history.go(-1)},autologin:"on"===$("#autologin").val()};n=function(a){a.nowait||$.mobile.showPageLoadingMsg();$.ajax({url:"svc/"+a.svc+".svc/"+a.method,type:"POST",dataType:"json",contentType:"application/json;charset=utf-8",data:JSON.stringify(a.data),processdata:!1,complete:function(){if(!a.nowait)return $.mobile.hidePageLoadingMsg(),"function"===
typeof a.complete?a.complete():void 0},success:function(b,c,d){if(!a.nowait){if(null!=b&&"d"in b)return"function"===typeof a.callback?a.callback(b.d):void 0;alert("Network Error");return console.log("err",d,d.statusText)}},error:function(a){alert("Network Error");return console.log("err",a,a.statusText)}});return!1};try{app.user=JSON.parse(sessionStorage.user||localStorage.user),0<(null!=(z=app.user)?z.uid:void 0)&&32===(null!=(A=app.user)?null!=(B=A.sid)?B.length:void 0:void 0)?(location.hash="#home",
n({svc:"user",method:"check",data:{uid:app.user.uid,sid:app.user.sid},callback:function(a){console.log("check",a);a||$.mobile.changePage("#login",{transition:"none"});return null}})):location.hash="#login"}catch(F){app.user=null,location.hash="#login"}console.log("app.user",app.user);app.save_profile=window.onbeforeunload=function(){var a;if(null!=(a=app.user)&&a.uid){if(a=sessionStorage.user=JSON.stringify(app.user),app.autologin)localStorage.user=a}else localStorage.removeItem("user"),sessionStorage.removeItem("user")};
$('[data-role="page"] [data-role="header"]:not(.ui-non-nav)').append($('[data-btn-role="back"],[data-btn-role="home"]'));$('#search [data-btn-role="home"]').hide();m=document.body;w=$(document.querySelectorAll('[data-role="map"]'));$(window).resize(function(){console.log("resize",m.clientWidth,m.clientHeight);app.horizontal=m.clientWidth>m.clientHeight;return $(m)[app.horizontal?"addClass":"removeClass"]("horizontal")});$(document.body).resize();$("#home").one({pageshow:function(){return f.el.offset($("#home_map").offset())}});
f=app.map=new google.maps.Map($("#map")[0],{zoom:15,mapTypeId:google.maps.MapTypeId.ROADMAP,navigationControl:!0,navigationControlOptions:{style:google.maps.NavigationControlStyle.SMALL}});s=new google.maps.places.PlacesService(f);v=new google.maps.Geocoder;u=new google.maps.DirectionsService;o=new google.maps.DirectionsRenderer;y=new google.maps.LatLngBounds(new google.maps.LatLng(38.052417,-122.728271),new google.maps.LatLng(37.247821,-121.552734));(function(){this.el=$("#map");(new google.maps.TrafficLayer).setMap(this);
return $.extend(this,{setMarkers:p(function(a){console.log("markers",a);a?$.isArray(a)||(a=[a]):a=null;null!=this.markers&&this.markers.forEach(function(a){return a.setMap(null)});this.markers=null!=a?a.map(function(a){a.map=f;return new google.maps.Marker(a)}):null;return this},this),getCurPos:p(function(a,b){null==b&&(b=a,a=!0);null!=navigator.geolocation&&navigator.geolocation.getCurrentPosition(p(function(c){var d;d=new google.maps.LatLng(c.coords.latitude,c.coords.longitude);console.log("curlatlng",
d);if(!d.equals(this.getCenter()))d.changed=!0;return a&&d.changed?(this.setMarkers(null),this.setCenter(d),w.each(p(function(a,b){return $(b).css("background-image","url('https://maps.googleapis.com/maps/api/staticmap?center="+d.lat()+","+d.lng()+"&zoom="+($(b).attr("data-map-zoom")||15)+"&size="+$(window).width()+"x"+this.el.height()+"&maptype=roadmap&format=png8&sensor=true&language=en')")},this)),v.geocode({latLng:d},p(function(a,c){var f;c===google.maps.GeocoderStatus.OK?b.call(this,d,null!=
(f=a[0])?f.formatted_address:void 0):alert("Geocoder failed due to: "+c+"\n App terminated!");return this.setCenter(d)},this))):b.call(this,d)},this),function(){return alert("App cannot run without geo location!")});return this},this)})}).call(f);$('[data-role="page"]').bind({pagebeforeshow:function(){return f.el.css({opacity:0,"z-index":0})},pageshow:function(){var a,b;$.mobile.fixedToolbars.show();this.hh=(null!=(a=$('[data-role="header"]',this))?a.outerHeight():void 0)||0;this.fh=(null!=(b=$('[data-role="footer"]',
this))?b.outerHeight():void 0)||0;this.bh=document.body.clientHeight-this.hh-this.fh;$(".map",this).add(f.el).height(this.bh*(app.horizontal?1:0.45));if($(this).hasClass("has-map"))return f.el.css({opacity:1,"z-index":1E4})}});console.log("user",app.user);$.ajax({url:"gapi?&hl=en-us&weather=san+jose,ca",dataType:"xml",success:function(a){var b,c,a=C(a);if(null!=(null!=(b=a.weather)?b.current_conditions:void 0))return b=a.weather.current_conditions,console.log("w:",a),c=function(a){return"https://www.google.com"+
a.icon.data},$("#weather").html('<div id="weather_now" class="weather"><img src="'+c(b)+'"/>'+b.condition.data+"<br/>"+b.temp_f.data+"\u00b0F</div>").append(a.weather.forecast_conditions.map(function(a){return'<div class="weather"><img src="'+c(a)+'"/>'+a.day_of_week.data+" "+a.high.data+"/"+a.low.data+"\u00b0F</div>"}).join("")),this},error:function(a){return console.log("get weather failed",a)}});r=function(a,b){return t("KnightRiderX\u00b5\u0004\u0005\u00f1PGo\u00f0@\u00d8\u00f4\u00ed\u009d\u00d2y\u00c0n\u00a6\u00d9\u00ffKnightRider"+
a+t("KnightRiderX\u00b5\u0004\u0005\u00f1PGo\u00f0@\u00d8\u00f4\u00ed\u009d\u00d2y\u00c0n\u00a6\u00d9\u00ffKnightRider"+a+"\u00ff"+b+"KnightRiderX\u00b5\u0004\u0005\u00f1PGo\u00f0@\u00d8\u00f4\u00ed\u009d\u00d2y\u00c0n\u00a6\u00d9\u00ffKnightRider")+b+"KnightRiderX\u00b5\u0004\u0005\u00f1PGo\u00f0@\u00d8\u00f4\u00ed\u009d\u00d2y\u00c0n\u00a6\u00d9\u00ffKnightRider")};$("#home").bind({pagebeforeshow:function(){if(!$("#map",this).length)return console.log("home pageshow"),f.getCurPos(function(a,b){null!=
b&&$("#home_addr").text(b);this.setZoom(15);return this.setMarkers({position:a})}),this}});$("#login").bind({pagecreate:function(){$("#login_form").submit(function(a){var b,c,d,f;a.preventDefault();a.stopPropagation();d=$("input",this).textinput("disable");f=$("select",this).slider("disable");b=$("button",this).button("disable");$("#btn_reg").addClass("ui-disabled");c=$("#email").val().trim();a=$("#password").val();if(!c||!a)return!1;a=r(c.toLowerCase(),a);app.autologin="on"===$("#autologin").val();
n({svc:"user",method:"login",data:{email:c,password:a},callback:function(a){var b;console.log(a);return a.uid&&32===(null!=(b=a.sid)?b.length:void 0)?(app.user={uid:a.uid,email:c,sid:a.sid},$.mobile.changePage("#home",{transition:"flip"})):alert("Login Failed, please try again")},complete:function(){b.button("enable");d.textinput("enable");f.slider("enable");return $("#btn_reg").removeClass("ui-disabled")}});return!1});return this},pagebeforehide:function(){return $("#login_form_warp").hide()},pagebeforeshow:function(){return $("#login_form_warp").hide()},
pageshow:function(){$("#password").val("");$("#login_form_warp").show();console.log("logout",app.user);if(null!=app.user)return n({svc:"user",method:"logout",nowait:!0,data:{uid:app.user.uid,sid:app.user.sid}}),app.user=null,app.save_profile(),this}});$("#reg_form").submit(function(a){var b,c;a.preventDefault();a.stopPropagation();if(this.password.value!==this.password2.value)return alert("Password does not match!"),this.password2.focus(),!1;a=this.email.value.trim();b=this.password.value;b=r(a.toLowerCase(),
b);c={email:a,password:b,fullname:{first:this.first.value.trim(),last:this.last.value.trim()},phone:this.phone.value.trim()};console.log("reg",c);n({svc:"user",method:"reg",data:{user:c},callback:function(a){console.log("new id:",a);if(1>a)return alert("Email already exists!");$("#email").val(c.email);$("#reg").dialog("close");return alert("Registration successful!")}});return!1});$("#appointment").bind({pagebeforeshow:function(){var a,b;$("#datetime").val(Date(Date.parse(new Date)+36E5).toLocaleString());
32!==(null!=(a=app.user)?null!=(b=a.sid)?b.length:void 0:void 0)&&$.mobile.changePage("#login",{transition:"flip",reverse:!0});return!1}});$("#appt_form").submit(function(a){var b,c,d;if(32!==(null!=(b=app.user)?null!=(c=b.sid)?c.length:void 0:void 0)||0===(null!=(d=app.user)?d.uid:void 0))return!1;a.preventDefault();a.stopPropagation();a={user:app.user.uid,place:app.selected_place.id,contact:{name:this.name.value,phone:this.phone.value},datetime:"/Date("+Date.parse(this.datetime.value)+"-0000)/",
message:this.comments.value};console.log("appt",a);n({svc:"appointment",method:"add",data:{appt:a,sid:app.user.sid},callback:function(a){console.log("appt success:",a);return a?($("#appointment").dialog("close"),alert("Appointment sent successful!")):$.mobile.changePage("#login",{transition:"flip",reverse:!0})}});return!1});$('[data-btn-role="search"]').live({vclick:function(){app.search_keyword=$(this).text();console.log("vclick",app.search_keyword);return this}});app.custom_search_history_refresh=
function(){var a,b;$("#custom_history_list li:gt(0)").remove();a='<li data-role="list-divider" class="ui-body-c list-none">(None)</li>';if(null!=(b=app.user.custom_search_history)&&b.length)a=app.user.custom_search_history.map(function(a){return'<li><a href="#result" data-btn-role="search">'+a+"</a></li>"}).join("");return $("#custom_history_list_header").after(a)};app.place_search_history_refresh=function(){var a,b;$("#search_history_list li:gt(0)").remove();a='<li data-role="list-divider" class="ui-body-c list-none">(None)</li>';
if(null!=(b=app.user.place_search_history)&&b.length)a=app.user.place_search_history.map(function(a,b){return'<li><a href="#detail" data-btn-role="result" data-index="'+b+'"><img src="'+a.icon+'" class="ui-li-icon"><h3 class="ui-li-heading">'+a.name+'</h3><p class="ui-li-desc">'+a.vicinity+"</p></li>"}).join("");return $("#search_history_list_header").after(a)};$("#custom_search").bind({pagecreate:function(){this.created=!0;app.custom_search_history_refresh();return new google.maps.places.Autocomplete($("#input_search")[0],
{bounds:y,types:["establishment"]})}});$("#custom_search").bind("pageshow pagebeforeshow",function(){if(this.created)return $("#custom_history_list").listview("refresh")});$("#custom_search_form").submit(function(){var a,b;a=$("#input_search");(b=$.trim(a.val()))?(app.search_keyword=new String(b),app.search_keyword.custom=!0,$.mobile.changePage("#result"),console.log("vclick",app.search_keyword)):a.focus().val("");return!1});$("#search_history").bind({pagecreate:function(){this.created=!0;app.place_search_history_refresh();
return $("#search_history li a").live({vclick:function(){return app.selected_place=app.user.place_search_history[Number($(this).attr("data-index"))]}})}});$("#search_history").bind("pageshow pagebeforeshow",function(){if(this.created)return $("#search_history_list").listview("refresh")});$("#result").bind({pagebeforeshow:function(){var a;console.log("search for",app.search_keyword);if(app.search_keyword)return $.mobile.showPageLoadingMsg(),a=$("#result_list").empty(),f.getCurPos(function(b){this.setZoom(12);
return s.search({location:b,radius:5E3,keyword:app.search_keyword},function(c,d){var h,i,j;if(d===google.maps.places.PlacesServiceStatus.ZERO_RESULTS)alert("Zero Result"),app.back();else if(d===google.maps.places.PlacesServiceStatus.OK){if($("#result_addr").text(""+app.search_keyword+" ("+c.length+")"),a.height(document.body.clientHeight-a.offset().top),console.log("search result",c),app.result_map={},c.forEach(function(a){var c,d;app.result_map[a.id]=a;a=a.geometry;d=a.location.lng()-b.lng();c=a.location.lat()-
b.lat();return a.dist=Math.pow(d,2)+Math.pow(c,2)}),c.sort(function(a,b){return a.geometry.dist-b.geometry.dist}),c=c.slice(0,25),a.append(c.map(function(a,b){var c;a.seq=String.fromCharCode(65+b);return'<li><a href="#detail" data-btn-role="result" id="'+a.id+'"><div style="float:left">'+a.seq+'</div><img src="'+(null!=(c=a.icon)?c.replace(/^http:/,"https:"):void 0)+'" class="ui-li-icon"><h3 class="ui-li-heading">'+a.name+'</h3><p class="ui-li-desc">'+a.vicinity+"</p></li>"}).join("")),h=c.reverse().map(function(a){return{position:a.geometry.location,
icon:"https://www.google.com/mapfiles/marker"+a.seq+".png",title:a.name}}),a.listview("refresh"),h.push({position:b,icon:"https://www.google.com/mapfiles/arrow.png",title:"You are here"}),f.setMarkers(h),app.search_keyword.custom&&(h=null!=(j=(i=app.user).custom_search_history)?j:i.custom_search_history=[],0===h.length||h[0]!==app.search_keyword))h.unshift(app.search_keyword),app.custom_search_history_refresh()}else alert("Search Error");return this})}),this;app.back()}});x=function(a){var b,c,a=
Number(a);c=a.toFixed(1);b=a|0;0<b&&(c+=" "+Array(b+1).join('<img src="res/star.png"/>'));0.4<a-b&&(c+='<img src="res/halfstar.png"/>');return c};$("#result_list a").live({vclick:function(){console.log(this.id);return app.selected_place=app.result_map[this.id]}});$("#detail").bind({pagecreate:function(){return $("#apt_cancel").bind({vclick:function(a){a.preventDefault();a.stopPropagation();$("#appointment").dialog("close");return!1}})},pageshow:function(){var a,b;a=$("#detial_info");a.height(document.body.clientHeight-
a.offset().top-this.fh);console.log("detailof",app.selected_place);window.scrollTop=0;if(app.selected_place)return b=function(b){var d,h,i,j;f.setCenter(b.geometry.location);f.setMarkers({position:b.geometry.location});f.setZoom(15);$("#detail_place").text(b.name);a.html("<ul><li>"+b.formatted_address+"</li><li>"+b.formatted_phone_number+"</li><li>"+b.types.join(", ").replace(/_/g," ").toUpperCase()+"</li><li>"+(null!=b.rating?x(b.rating):"(No Rating Data)")+'</li><li><a href="'+(b.website||b.url)+
'" target="_blank">'+(null!=b.website?"Visit its Website":"View on Google Place")+"</a></li></ul>");d=null!=(i=(h=app.user).place_search_history)?i:h.place_search_history=[];if(0===d.length||d[0].id!==app.selected_place.id)d.some(function(a,b){return a.id===app.selected_place.id?(d.splice(b,1),!0):!1}),d.unshift({id:b.id,reference:app.selected_place.reference,name:b.name,vicinity:b.vicinity,icon:null!=(j=b.icon)?j.replace(/^http:/,"https:"):void 0}),app.place_search_history_refresh();console.log(b);
return this},app.selected_place.__detail?b(app.selected_place.__detail):s.getDetails({reference:app.selected_place.reference},function(a,d){if(d===google.maps.places.PlacesServiceStatus.OK)return app.selected_place.__detail=a,b(a)}),this;app.back()}});$("#direction").bind({pagebeforeshow:function(){var a;a=$("#direction_panel");a.height(document.body.clientHeight-a.offset().top);return f.getCurPos(function(b,c){return u.route({origin:c,destination:app.selected_place.vicinity,travelMode:google.maps.DirectionsTravelMode.DRIVING,
unitSystem:google.maps.DirectionsUnitSystem.IMPERIAL,provideRouteAlternatives:!0},function(b,c){return c===google.maps.DirectionsStatus.OK?(o.setMap(f),o.setPanel(a[0]),o.setDirections(b)):alert("Directions failed: "+c)})})},pagehide:function(){return o.setMap(null)}});console.log(2)}).call(this);
